<a href="https://colab.research.google.com/github/laatu08/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Numpy is faster than traditional list
import numpy as np

# to create numpy, we use array method
a = np.array([1,2,3,4,5])
b = np.array((6,7,8,9,0),dtype='f')

In [2]:
print(a)
print(b)

[1 2 3 4 5]
[6 7 8 9 0]


In [3]:
# type of a and b will no longer be list or tuple
type(a)

numpy.ndarray

In [5]:
# to find data type of data in numpy, we use dtype
a.dtype
b.dtype

dtype('int64')

In [8]:
b.dtype

dtype('float32')

In [ ]:
# Dimensions in numpy

In [9]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
# ndim give the number of dimension
a.ndim

2

In [11]:
a[0]

array([1, 2, 3])

In [12]:
a[0,2]

3

In [18]:
# error if different size
b = np.array([[1,2,3],[4,5,7]])

In [19]:
b.ndim

2

In [20]:
b[1,1]

5

In [21]:
c = np.array([[[1,2,3],[4,5,6],[0,0,-1]],[[-1,-2,-3],[-4,-5,-6],[0,0,1]]])

In [22]:
c.ndim

3

In [23]:
c[1,1,1]

-5